using System;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace FluxFormula.BlobRegistry.Generator
{
    /// <summary>
    /// 增量 source generator：读取 blob 二进制文件，生成 BlobRegistry.g.cs。
    /// </summary>
    /// <remarks>
    /// <para>输入：.bytes 文件（通过 AdditionalFiles 或项目目录 fallback）</para>
    /// <para>输出：<c>BlobRegistry.g.cs</c>——实现 <c>IFluxBlobRegistry</c> 的 internal 类，
    /// 包含编译期固化的偏移表常量 + assembly-level <c>FluxBlobRegistryAssembly</c> attribute。</para>
    /// </remarks>
    [Generator]
    public class BlobRegistryGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // 管道：查找所有 .bytes AdditionalFiles，提取路径
            var blobPaths = context.AdditionalTextsProvider
                .Where(text => text.Path.EndsWith(".bytes", StringComparison.OrdinalIgnoreCase))
                .Select((text, _) => text.Path)
                .Collect();

            // 合并 MSBuild 项目目录（用于 fallback）
            var projectDir = context.AnalyzerConfigOptionsProvider
                .Select((options, _) =>
                    options.GlobalOptions.TryGetValue("build_property.MSBuildProjectDirectory", out var dir)
                        ? dir
                        : null);

            var combined = blobPaths.Combine(projectDir);

            context.RegisterSourceOutput(combined, (spc, source) =>
            {
                var (paths, projDir) = source;

                string? blobPath = null;

                // 优先使用 AdditionalFiles
                if (paths.Length > 0)
                {
                    blobPath = paths[0];
                }
                // Fallback: 项目目录下的已知路径
                else if (!string.IsNullOrEmpty(projDir))
                {
                    string fallback = Path.Combine(projDir, "Assets", "StreamingAssets", "flux.bytes");
                    if (File.Exists(fallback))
                        blobPath = fallback;
                }

                if (blobPath == null || !File.Exists(blobPath))
                {
                    // 无 blob 文件——生成空 stubs 保证编译通过
                    spc.AddSource("BlobRegistry.g.cs",
                        SourceText.From(EmptyRegistrySource, Encoding.UTF8));
                    return;
                }

                try
                {
                    byte[] fileBytes = File.ReadAllBytes(blobPath);
                    var (header, entries) = BinaryBlobReader.Read(fileBytes);

                    // 从文件名提取 BlobKey
                    string blobKey = Path.GetFileNameWithoutExtension(blobPath);

                    string sourceCode = GenerateRegistry(header, entries, blobKey);
                    spc.AddSource("BlobRegistry.g.cs",
                        SourceText.From(sourceCode, Encoding.UTF8));
                }
                catch (Exception ex)
                {
                    // 解析失败——报告诊断并生成空 stub
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "FLXB001", "Blob Parse Error",
                            $"Failed to parse blob file '{blobPath}': {{0}}",
                            "FluxFormula", DiagnosticSeverity.Warning, isEnabledByDefault: true),
                        Location.None, ex.Message));

                    spc.AddSource("BlobRegistry.g.cs",
                        SourceText.From(EmptyRegistrySource, Encoding.UTF8));
                }
            });
        }

        // ═══════════════════════════════════════════════════════
        // 代码生成
        // ═══════════════════════════════════════════════════════

        private static string GenerateRegistry(
            BinaryBlobReader.BlobHeader header,
            BinaryBlobReader.BlobEntry[] entries,
            string blobKey)
        {
            var sb = new StringBuilder();

            // Header
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// FluxFormula Blob Registry — generated by FluxFormula.BlobRegistry.Generator");
            sb.AppendLine($"// Entries: {header.EntryCount}, BlobDataSize: {header.BlobDataSize} bytes");
            sb.AppendLine($"// BlobKey: {blobKey}");
            sb.AppendLine();
            sb.AppendLine("using FluxFormula.Core;");
            sb.AppendLine();

            // Assembly attribute
            sb.AppendLine("[assembly: FluxBlobRegistryAssembly]");
            sb.AppendLine();

            // Namespace + class
            sb.AppendLine("namespace FluxFormula.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal sealed class BlobRegistry : IFluxBlobRegistry");
            sb.AppendLine("    {");
            sb.AppendLine($"        public int EntryCount => {header.EntryCount};");
            sb.AppendLine($"        public string BlobKey => \"{EscapeString(blobKey)}\";");
            sb.AppendLine();

            // Entries array
            if (header.EntryCount == 0)
            {
                sb.AppendLine("        private static readonly BlobEntry[] _entries =");
                sb.AppendLine("            System.Array.Empty<BlobEntry>();");
                sb.AppendLine();
                sb.AppendLine("        public BlobEntry[] GetEntries() => _entries;");
            }
            else
            {
                sb.AppendLine($"        private static readonly BlobEntry[] _entries = new BlobEntry[{header.EntryCount}]");
                sb.AppendLine("        {");

                for (int i = 0; i < entries.Length; i++)
                {
                    var e = entries[i];
                    sb.Append($"            new BlobEntry(");
                    sb.Append($"new DualHash64(0x{e.XxHash64:X16}UL, 0x{e.FnvHash64:X16}UL), ");
                    sb.Append($"{e.Offset}, {e.Length})");

                    if (i < entries.Length - 1)
                        sb.AppendLine(",");
                    else
                        sb.AppendLine();
                }

                sb.AppendLine("        };");
                sb.AppendLine();
                sb.AppendLine("        public BlobEntry[] GetEntries() => _entries;");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        // ═══════════════════════════════════════════════════════
        // 无 blob 文件时的空 stub
        // ═══════════════════════════════════════════════════════

        private const string EmptyRegistrySource = @"// <auto-generated />
// FluxFormula Blob Registry — no .bytes file found, empty stubs generated.

using FluxFormula.Core;

[assembly: FluxBlobRegistryAssembly]

namespace FluxFormula.Generated
{
    internal sealed class BlobRegistry : IFluxBlobRegistry
    {
        public int EntryCount => 0;
        public string BlobKey => string.Empty;

        private static readonly BlobEntry[] _entries =
            System.Array.Empty<BlobEntry>();

        public BlobEntry[] GetEntries() => _entries;
    }
}
";

        // ═══════════════════════════════════════════════════════
        // 工具
        // ═══════════════════════════════════════════════════════

        private static string EscapeString(string s)
        {
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
