name: Test Unity Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testRunner:
    name: Unity ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      checks: write
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2022.3.62f3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Run Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Tests/TestProject
          unityVersion: ${{ matrix.unityVersion }}
          testMode: all
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # customParameters: -ignoreCompilerErrors

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test-results
          path: artifacts
